### ISSUE TITLE
Feature request: Basic linting for composite actions

### ISSUE THREAD

**Issue by JavaScriptBach** [rhysd/actionlint#245] opened 2022-11-02 21:22 UTC
What do you think about adding some basic support for linting composite `action.yml` files? For example:

- Missing `shell:` attribute for steps
- Attempts to access `${{ secrets.* }}`

These are common mistakes that I make when writing actions. In general this project has helped me a lot when writing workflows, and I'd love to get its benefits extended to writing actions!

**Comment by andreypotapov-tomtom** [comment] 2022-11-03 10:27
Seems like a duplicate of https://github.com/rhysd/actionlint/issues/46

**Comment by AndreyNautilus** [comment] 2022-11-03 10:27
Seems like a duplicate of https://github.com/rhysd/actionlint/issues/46

**Comment by rhysd** [comment] 2022-11-03 15:24
Yes, this is duplicate of #46.

**Closed by rhysd** 2022-11-03 15:24 UTC
