### ISSUE TITLE
Strategy can be used when reusable workflows are called

### ISSUE THREAD

**Issue by ChipWolf** [rhysd/actionlint#203] opened 2022-08-24 17:10 UTC
```
when a reusable workflow is called with "uses", "strategy" is not available. only following keys are allowed: "name", "uses", "with", "secrets", "needs", "if", and "permissions" in job "build-matrix" [syntax-check]
```

**Comment by rhysd** [comment] 2022-08-25 00:12
duplicate of #197

**Closed by rhysd** 2022-08-25 00:12 UTC
