### ISSUE TITLE
[Feature request] Add support to lint custom action files

### ISSUE THREAD

**Issue by tddschn** [rhysd/actionlint#200] opened 2022-08-24 03:15 UTC
## Custom action files?

Actions authors put their custom action files (`action.yml` in the root directory by convention, but could be anywhere with any names) in GitHub repositories so that other can use those custom actions with the `uses` syntax.

However, actionlint currently doesn't seem to understand the custom action yaml files, and complain about things like missing `jobs` section.

## Why?

actionlint enables workflow authors to write workflow files confidently, and catches errors early.   
It would also greatly benefit action authors if actionlint supports linting custom action files.

**Comment by rhysd** [comment] 2022-08-24 08:59
Duplicate of #46. It would be nice to have, but there is not enough velocity to implement.

**Closed by rhysd** 2022-08-24 08:59 UTC
