### ISSUE TITLE
Wrong cursor placement for shellcheck results

### ISSUE THREAD

**Issue by mcandre** [rhysd/actionlint#462] opened 2024-10-20 20:50 UTC
The shellcheck output always shows a cursor pointed at the wrong column of GitHub Actions command entries. The output points at the `run` key, when in fact the shellcheck violation is much further along the YAML line.

One strategy involves hiding this cursor, until the correct column can be established. Work with shellcheck to pursue an option to elide column information.

**Comment by rhysd** [comment] 2024-10-21 09:46
This is a duplicate of long standing issue #88. There is no way to point the accurate position on the YAML file. This is current restriction of go-yaml I believe.

**Closed by rhysd** 2024-10-21 09:46 UTC
